security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: YouFood\RestaurantBundle\Entity\User, property: username }

    encoders:
        YouFood\RestaurantBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /user/redirectBasedOnRole
            logout:
                path: /logout
                target: /